/* Usage: PLAYWRIGHT_MODULE=/absolute/playwright CHROMIUM_PATH=/absolute/chromium node .droidrooter/browser-audit.cjs */
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');
const EXCLUDED=new Set(JSON.parse(fs.readFileSync(path.join(root,'docs/theme-redesign/static-audit.json'))).excluded_pages||[]);
const inventory=JSON.parse(fs.readFileSync(path.join(root,'docs/theme-redesign/static-audit.json'))).routes;
const output=process.env.AUDIT_SCREENSHOTS||'/tmp/droidrooter-theme-screenshots';fs.mkdirSync(output,{recursive:true});
const templates=['index.html','blog/index.html','blog/android-debloating-guide-2026/index.html','services/index.html','services/android-rooting/index.html','devices/index.html','devices/samsung/index.html','pricing/index.html','contact/index.html','about/index.html','how-it-works/index.html','portfolio/index.html','locations/usa/index.html','team/saad-nahid/index.html','privacy/index.html','faq/index.html','glossary/index.html','tools/rootability-checker/index.html','404.html','drvcam/control/index.html'];
(async()=>{
 const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end('Not found')}res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.json':'application/json','.ico':'image/x-icon'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']});
 const results=[];let next=0;const jobs=inventory.filter(x=>!x.redirect);
 async function worker(){const context=await browser.newContext({reducedMotion:'reduce'});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());const page=await context.newPage();let errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))missing.push({url:r.url().replace(base,''),status:r.status()})});
 while(next<jobs.length){const {file}=jobs[next++];const url=file==='index.html'?'/':('/'+file.replace(/\/index.html$/,''));errors=[];missing=[];try{
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+url,{waitUntil:'load',timeout:30000});await page.evaluate(()=>{for(const k of ['droidrooter-color-mode','droidrooter-design','drvcam.admin.theme'])localStorage.removeItem(k)});await page.reload({waitUntil:'load'});await page.waitForTimeout(80);
 const initial=(await page.locator('html').getAttribute('data-design'))+'/'+(await page.locator('html').getAttribute('data-color-mode'));const states=[];
 const kind=file.startsWith('drvcam/')?'console':EXCLUDED.has(file)?'excluded':'public';
 const designs=[null];const modes=kind==='excluded'?[null]:['dark','light'];
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});for(const design of designs){for(const mode of modes){
 if(design&&await page.locator('html').getAttribute('data-design')!==design)await page.locator('[data-design-toggle]').click();
 if(mode&&await page.locator('html').getAttribute('data-color-mode')!==mode){if(kind==='console'&&!(await page.locator('[data-theme-toggle]').isVisible()))await page.evaluate(m=>{document.documentElement.dataset.theme=m},mode);else await page.locator('[data-theme-toggle]').click();}await page.waitForTimeout(50);
 const state=await page.evaluate((EXCLUDED_PATHS)=>{const viewport=innerWidth;const bad=[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.position!=='fixed'&&s.visibility!=='hidden'&&(r.right>viewport+2||r.left< -2)&&!e.closest('pre,.dr-table-wrap,.dr-code')}).slice(0,12).map(e=>({tag:e.tagName,class:e.className,width:Math.round(e.getBoundingClientRect().width),right:Math.round(e.getBoundingClientRect().right)}));const ctl=document.querySelector('[data-theme-controls]');const covered=ctl?[...ctl.querySelectorAll('button')].filter(b=>{const r=b.getBoundingClientRect();if(!r.width)return false;const hit=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return hit&&!b.contains(hit)}).map(b=>b.className):[];return {design:document.documentElement.dataset.design,mode:document.documentElement.dataset.colorMode,width:viewport,covered,scrollWidth:document.documentElement.scrollWidth,overflow:document.documentElement.scrollWidth>viewport+2,overflowElements:bad,invisibleText:[...document.querySelectorAll('button,a,label,h1,h2,h3,p,td,th')].filter(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return r.width&&r.height&&e.textContent.trim()&&c.color===c.backgroundColor&&c.color!=='rgba(0, 0, 0, 0)'}).map(e=>({tag:e.tagName,class:e.className,text:e.textContent.trim().slice(0,80)})),buttonVisible:(()=>{if(location.pathname.startsWith('/drvcam/')||EXCLUDED_PATHS.includes(location.pathname))return true;const c=document.querySelector('[data-theme-controls]');return !!c&&!c.hidden&&c.getBoundingClientRect().width>0})(),brokenImages:[...document.images].filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.getAttribute('src'))}},[...EXCLUDED].map(f=>'/'+f.replace(/\/index.html$/,'')));states.push(state);
 if(templates.includes(file)&&((width===1440&&mode==='light')||(width===390&&mode==='dark')||(width===1440&&mode==='dark')))await page.screenshot({path:path.join(output,file.replaceAll('/','_')+'-'+(design||kind)+'-'+(mode||'na')+'-'+width+'.png')});
 }}}
 await page.reload({waitUntil:'load'});const persisted=(await page.locator('html').getAttribute('data-design'))+'/'+(await page.locator('html').getAttribute('data-color-mode'));results.push({file,kind,initial,persisted,states,errors:[...new Set(errors)],missing});
 }catch(e){results.push({file,error:e.message,errors,missing})}
 if(results.length%20===0)console.log('Reviewed',results.length,'/',jobs.length);
 }await context.close()}
 await Promise.all(Array.from({length:4},worker));
 // All legacy redirect destinations must resolve to their existing canonical routes.
 const redirContext=await browser.newContext();await redirContext.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());const p=await redirContext.newPage();const redirects=[];
 for(const {file} of inventory.filter(x=>x.redirect)){const html=fs.readFileSync(path.join(root,file),'utf8');const match=html.match(/http-equiv=["']refresh["'][^>]*content=["'][^"']*url=([^"'>]+)/i)||html.match(/content=["'][^"']*url=([^"'>]+)["'][^>]*http-equiv=["']refresh/i);if(!match){redirects.push({file,error:'No target'});continue}const expected=new URL(match[1],base).pathname.replace(/\/$/,'');try{await p.goto(base+'/'+file.replace(/\/index.html$/,''));await p.waitForURL(u=>u.pathname.replace(/\/$/,'')===expected,{timeout:5000});redirects.push({file,target:expected,pass:true})}catch(e){redirects.push({file,error:e.message})}}
 const interactions=[];
 const assert=require('node:assert/strict');
 await p.setViewportSize({width:390,height:844});await p.goto(base+'/');
 await p.locator('[data-dr-toggle]').click();assert.equal(await p.locator('[data-dr-toggle]').getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await p.locator('[data-dr-toggle]').getAttribute('aria-expanded'),'false');interactions.push('Mobile navigation opens and Escape closes');
 await p.locator('[data-theme-toggle]').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('html').getAttribute('data-color-mode'),'light');await p.goto(base+'/services');assert.equal(await p.locator('html').getAttribute('data-color-mode'),'light');await p.goto(base+'/blog');assert.equal(await p.locator('html').getAttribute('data-design'),'command');assert.equal(await p.locator('html').getAttribute('data-color-mode'),'light');interactions.push('Keyboard dark/light switch; preference persists across navigation; design stays Command Center');
 await p.goto(base+'/blog/android-debloating-guide-2026');const faq=p.locator('details').first();await faq.locator('summary').click();assert.equal(await faq.getAttribute('open'),'');interactions.push('Article FAQ opens');
 await p.locator('.dr-code-copy').first().click();interactions.push('Code copy control clickable (clipboard permission varies by browser)');
 await p.goto(base+'/tools/rootability-checker');await p.locator('input').first().fill('Pixel 8');await p.waitForTimeout(350);assert.ok((await p.locator('main').innerText()).includes('Pixel 8'));interactions.push('Rootability checker accepts device search');
 await p.goto(base+'/contact');assert.ok(await p.locator('main').count());interactions.push('Contact page renders; no external submissions made');
 await p.goto(base+'/drvcam/control');for(const mode of ['dark','light']){if(await p.locator('html').getAttribute('data-color-mode')!==mode)await p.locator('[data-theme-toggle]').click();assert.ok(await p.locator('.btn.primary').evaluate(e=>getComputedStyle(e).color!==getComputedStyle(e).backgroundColor));}interactions.push('Dashboard primary action contrast in both modes; authenticated/API operations not exercised');
 const blocked=await browser.newContext();await blocked.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('Storage denied')}})});const bp=await blocked.newPage();await bp.goto(base+'/');assert.equal(await bp.locator('html').getAttribute('data-color-mode'),'dark');await bp.locator('[data-theme-toggle]').click();assert.equal(await bp.locator('html').getAttribute('data-color-mode'),'light');await blocked.close();interactions.push('Storage unavailable: dark default and toggle still work');
 const nojs=await browser.newContext({javaScriptEnabled:false});await nojs.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());const np=await nojs.newPage();await np.goto(base+'/');assert.equal(await np.locator('html').getAttribute('data-color-mode'),'dark');assert.equal(await np.locator('[data-theme-controls]').isVisible(),false);assert.equal(await np.locator('html').getAttribute('data-design'),'command');await nojs.close();interactions.push('JavaScript disabled: dark page remains readable and inactive toggle hidden');
 await redirContext.close();await browser.close();server.close();const report={interactions,pages:results.length,renderedStates:results.reduce((n,r)=>n+(r.states?.length||0),0),results,redirects};fs.writeFileSync(path.join(root,'docs/theme-redesign/browser-audit.json'),JSON.stringify(report,null,2)+'\n');const expectPersist={public:'command/light',console:'command/light',excluded:'null/null'};const expectInitial={public:'command/dark',console:'command/dark',excluded:'null/null'};const failures=results.filter(r=>r.error||r.initial!==expectInitial[r.kind]||r.persisted!==expectPersist[r.kind]||r.states?.some(s=>s.overflow||!s.buttonVisible||s.invisibleText.length||(r.kind==='public'&&s.covered.length))||r.errors.length||r.missing.length);console.log(JSON.stringify({pages:results.length,states:report.renderedStates,failures,redirectFailures:redirects.filter(x=>!x.pass)},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
